apiVersion: v1
kind: Service
metadata:
  name: http_server
spec:
  selector:
    app: http_server
  ports:
    -port: 4200
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: http_server
Spec:
  replicas: 1
  selector:
    matchLabels:
      app: http_server
  template:
    metadata:
      labels:
        app: http_server
    spec:
      containers:
        -name: app
        image: haywardj/http_server
        ports:
          - containerPort: 8000
          imagePullPolicy: Always