apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  selector:
    app: http-server
  ports:
  - port: 4200
    targetPort: 8000
  loadBalancerIP: 127.0.0.1
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: app
        image: haywardj/http_server
        ports:
        - containerPort: 8000
        imagePullPolicy: Always